# Guest OS timezone
timezone: UTC

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: cxforms

# assign accessible domain name in browser
domain: cxforms.com

# Virtual machine IP
ip: 192.168.77.9

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 256
